# Base image
FROM node:18.16.0-alpine3.16 AS builder

# Run linux commands 

# Sets working directory
WORKDIR /planner

# Install the necessary dependencies
COPY package*.json ./
RUN npm install

# Copy from local file to container
COPY . .

# Build the application
RUN npm run build


# Final stage for app image
FROM node:18.16.0-alpine3.16 
WORKDIR /planner

COPY --from=builder /planner/build ./build

# Install a lightweight web server (e.g., serve)
RUN npm install -g serve

# start container with node and parameters: server.js
EXPOSE 4173
CMD ["serve", "-s", "build", "-l", "4173"]

